package com.utils.AOPTest;

import static org.junit.Assert.assertEquals;

import org.junit.Test;


public class TestInterceptorWithFilterTest {

	@Test 
	public void createProxy_A$() throws Exception {
		// TODO auto-generated by JUnit Helper.
		TestInterceptorWithFilter target = new TestInterceptorWithFilter();
		PersonServiceImpl actual = (PersonServiceImpl)target.createProxy();
		System.out.println(actual.getHead());
		actual.getPersonName(1);
		
		PersonServiceImpl test = new PersonServiceImpl();
		actual.save("camel");
	
		assertEquals(test.getHead(), actual.getHead());
	}
}
