package com.utils.AOPTest;

import org.junit.Test;


public class TestJavassitAOPTest {

	@Test 
	public void modifySaveMethod_A$() throws Exception {
		// TODO auto-generated by JUnit Helper.
		TestJavassitAOP target = new TestJavassitAOP();
		target.modifySaveMethod();
		
		PersonServiceImpl psi = new PersonServiceImpl();
		psi.aaa();
		psi.save("camel");
		String name = psi.getPersonName(1);
		System.out.println(name);
	}
}
